# Generated by Django 4.2.4 on 2023-10-10 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('icon', models.FileField(blank=True, null=True, upload_to='classifieds/category/icons/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Classified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('deleted', 'deleted')], default='draft', max_length=8)),
                ('title', models.CharField(max_length=150)),
                ('is_liked', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.category')),
            ],
            options={
                'verbose_name': 'Classified',
                'verbose_name_plural': 'Classifieds',
            },
        ),
        migrations.CreateModel(
            name='ClassifiedDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_type', models.CharField(choices=[('usd', 'USD'), ('uzs', 'UZS')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('classified', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classifieddetail', to='classifieds.classified')),
            ],
            options={
                'verbose_name': 'Classified Detail',
                'verbose_name_plural': 'Classified Details',
            },
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('classified_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.classifieddetail')),
            ],
            options={
                'verbose_name': 'Dynamic Field',
                'verbose_name_plural': 'Dynamic Fields',
            },
        ),
        migrations.CreateModel(
            name='ClassifiedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='classifieds/images/')),
                ('classified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiedimage_set', to='classifieds.classified')),
            ],
            options={
                'verbose_name': 'Classified Image',
                'verbose_name_plural': 'Classified Images',
            },
        ),
    ]
