version: '3.7'
services:
  kelishamiz_backend:
    volumes:
      - static:/static
      - media:/media
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    image: postgres:14.9
    environment:
      - MEDIA_URL=/media/
      - POSTGRES_DB=kelishamiz
      - POSTGRES_USER=murtazo
      - POSTGRES_PASSWORD=murtazo#1280

    volumes:
      - pgdata:/var/lib/posgresql/data
  nginx:
    build: ./deploy/nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - kelishamiz_backend

volumes:
  static:
  pgdata:
  media:
