version: '3.7'
services:
  kelishamiz_backend:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./deploy/nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - kelishamiz_backend

volumes:
  static:


