version: '3.9'

services:

  flower:
    build:
      context: ./
      dockerfile: docker/celery-flower/Dockerfile
    environment:
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - postgres
      - redis
      - celery-worker
    ports:
      - "5555:5555"

  backend:
    container_name: backend_container
    image: backend
    volumes:
      - .:/usr/src/app
      - static:/static
      - media:/app/config/media
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/backend/Dockerfile
    depends_on:
      - celery-worker
      - flower
    networks:
      - postgres
      - redis
      - backend
    ports:
      - "8000:8000"

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres

  proxy:
    build:
      context: ./docker/proxy
    restart: always
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/var/lib/letsencrypt:/var/lib/letsencrypt"
      - "static:/static"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - backend
    environment:
      - DOMAIN=${DOMAIN}

  celery-worker:
    restart: always
    build:
      context: ./
      dockerfile: docker/celery-worker/Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis
      - pgadmin
    environment:
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      REDIS_URL: redis://redis:6379/0
    networks:
      - postgres
      - redis
      - celery-worker

  redis:
    restart: unless-stopped
    image: redis:7-alpine
    networks:
      - redis

networks:
  backend:
  postgres:
    driver: bridge
  redis:
    driver: bridge
  celery-worker:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  static:
  media:
