version: '3.7'

services:

  kelishamiz_backend:
    image: backend
    volumes:
      - static:/static
    env_file:
      - .env
    networks:
      - backend
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:14.9
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    image: nginx
    build: ./deploy/nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - kelishamiz_backend
    networks:
      - backend

  celery:
    image: celery
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: celery -A kelishamiz worker --loglevel=info -E
    environment:
      - DJANGO_DB_HOST=db

  redis:
    image: redis:latest

volumes:
  pgdata:
  static:


networks:
  backend:
