[tool.poetry]
name = "kelishamiz-backend"
version = "0.1.0"
description = ""
authors = ["Murtazo <murtazox04@gmail.com>"]
license = "MIT License"
readme = "README.md"
packages = [{include = "kelishamiz_backend"}]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.4"
djangorestframework = "^3.14.0"
python-decouple = "^3.8"
requests = "^2.31.0"
pillow = "^10.0.0"
drf-yasg = "^1.21.7"
django-debug-toolbar = "^4.2.0"
djangorestframework-simplejwt = "^5.3.0"
eskiz-sms = "^0.2.3"
django-phonenumbers = "^1.0.1"
django-allauth = "^0.55.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
