# Generated by Django 4.2.4 on 2023-08-26 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addetail',
            old_name='dynamic_fields',
            new_name='dynamicFields',
        ),
        migrations.AlterField(
            model_name='addetail',
            name='ad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addetail', to='ads.ad'),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adimage_set', to='ads.ad'),
        ),
    ]
